### ISSUE TITLE
Investigate to remove the --report-unsupported-elements-at-runtime in native mode

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-mybatis#10]
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM 21.1.0 Java 11 CE (Java Version 11.0.11+8-jvmci-21.1-b05)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 1000:1000 -v /home/zhfeng/work/zhfeng/quarkiverse-mybatis/integration-tests/target/quarkus-mybatis-integration-tests-0.0.10-SNAPSHOT-native-image-source-jar:/project:z quay.io/quarkus/ubi-quarkus-native-image:21.1-java11 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=zh -J-Duser.country=CN -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar quarkus-mybatis-integration-tests-0.0.10-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-mybatis-integration-tests-0.0.10-SNAPSHOT-runner
[quarkus-mybatis-integration-tests-0.0.10-SNAPSHOT-runner:24]    classlist:   3,811.26 ms,  0.93 GB
[quarkus-mybatis-integration-tests-0.0.10-SNAPSHOT-runner:24]        (cap):     614.81 ms,  0.93 GB
[quarkus-mybatis-integration-tests-0.0.10-SNAPSHOT-runner:24]        setup:   2,597.72 ms,  0.93 GB
05:00:45,896 INFO  [org.jbo.threads] JBoss Threads version 3.4.0.Final
[quarkus-mybatis-integration-tests-0.0.10-SNAPSHOT-runner:24]     analysis:  27,040.59 ms,  2.74 GB
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing com.oracle.svm.reflect.Class_getEnclosingMethod0_8a7a0562f19e413046b2404928996c9b00e4e19e.invoke(java.lang.Object, java.lang.Object[]) 
Parsing context:
	parsing java.lang.reflect.Method.invoke(Method.java:566)
	parsing javax.enterprise.util.AnnotationLiteral.invoke(AnnotationLiteral.java:288)
	parsing javax.enterprise.util.AnnotationLiteral.getMemberValue(AnnotationLiteral.java:276)
	parsing javax.enterprise.util.AnnotationLiteral.hashCode(AnnotationLiteral.java:246)
	parsing java.lang.Object.toString(Object.java:246)
	parsing java.lang.String.valueOf(String.java:2951)
	parsing java.lang.StringBuilder.append(StringBuilder.java:168)
	parsing java.lang.Throwable.printStackTrace(Throwable.java:662)
	parsing java.lang.Throwable.printStackTrace(Throwable.java:648)
	parsing java.lang.Throwable.printStackTrace(Throwable.java:639)
	parsing com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:778)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:331)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:302)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:227)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:547)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.Class.getEnclosingMethod0() is reachable: The declaring class of this element has been substituted, but this element is not present in the substitution class
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:188)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:140)
	at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:140)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:409)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:389)
	at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:77)
	at com.oracle.graal.pointsto.infrastructure.UniverseMetaAccess.lookupJavaMethod(UniverseMetaAccess.java:93)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:66)
	at com.oracle.graal.pointsto.meta.AnalysisMetaAccess.lookupJavaMethod(AnalysisMetaAccess.java:39)
	at com.oracle.svm.reflect.hosted.ReflectionSubstitutionType$ReflectiveInvokeMethod.buildGraph(ReflectionSubstitutionType.java:586)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.buildGraph(AnalysisMethod.java:320)
	at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:78)
	at com.oracle.svm.hosted.SVMHost.parseBytecode(SVMHost.java:647)
	at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:592)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:163)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:304)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:313)
	... 13 more
Error: Image build request failed with exit status 1

```

**Comment by 362228416** [comment]
same problem.

**Comment by zhfeng** [comment]
I finally find that the root cause is that the graal does not static analyst the [Reflector.java](https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/reflection/Reflector.java) in the right way. It just assume the clazz is Class and add all of the get methods. So when we do ```method.invoke(...)```, it will throw such DeletedElementException.

I have a simple workaround which just check the type not equal Class.class. But I think it should be fixed in graal.

**Comment by zhfeng** [comment]
Because this happens during static analysis, subsitution will not be helpful here. And I write a simple test which only uses mybatis, it works by using native-image building. So I will raise an issue in upstream graal to find some helps.

**Comment by zakkak** [comment]
@zhfeng https://github.com/mybatis/mybatis-3/pull/2284 should solve this issue.

**Comment by zhfeng** [comment]
Thanks @zakkak for your investigating with this issue !

**Comment by zhfeng** [comment]
@zakkak I confirm that your fix with mybatis works. So hope it could be accepted

**Comment by zhfeng** [comment]
Now we get https://github.com/quarkiverse/quarkus-mybatis/pull/149 and I will revisit this issue very soon.
