### ISSUE TITLE
Type Aliases problem since 0.0.8

### ISSUE THREAD

**Issue by 9too** [quarkiverse/quarkus-mybatis#114]
# Issue

I use an XML configuration for type aliases like so :
```xml
    <typeAliases>
        <package name="org.acme.entity"/>
    </typeAliases>
    ...
    <mappers>
        <package name="org.acme.mapper"/>
    </mappers>
```

The problem is that since version 0.0.8 or more specifically commit 5517c67, this error occur during startup : 
```
Failed to start quarkus: java.lang.RuntimeException: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. The XML location is 'org/acme/mapper/MyMapper.xml'. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'MyEntity'.  Cause: java.lang.ClassNotFoundException: Cannot find class: MyEntity
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:109)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:225)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:206)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:484)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:389)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:64)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:54)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1450)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. The XML location is 'org/acme/mapper/MyMapper.xml'. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'MyEntity'.  Cause: java.lang.ClassNotFoundException: Cannot find class: MyEntity
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:123)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:95)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.loadXmlResource(MapperAnnotationBuilder.java:179)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:118)
	at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:72)
	at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:841)
	at io.quarkiverse.mybatis.runtime.MyBatisRecorder.addMappers(MyBatisRecorder.java:96)
	at io.quarkiverse.mybatis.runtime.MyBatisRecorder.createSqlSessionFactory(MyBatisRecorder.java:70)
	at io.quarkus.deployment.steps.MyBatisProcessor$generateSqlSessionFactory-687538554.deploy_0(MyBatisProcessor$generateSqlSessionFactory-687538554.zig:158)
	at io.quarkus.deployment.steps.MyBatisProcessor$generateSqlSessionFactory-687538554.deploy(MyBatisProcessor$generateSqlSessionFactory-687538554.zig:40)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:260)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:98)
	... 1 more
Caused by: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'MyEntity'.  Cause: java.lang.ClassNotFoundException: Cannot find class: MyEntity
	at org.apache.ibatis.builder.BaseBuilder.resolveClass(BaseBuilder.java:118)
	at org.apache.ibatis.builder.xml.XMLStatementBuilder.parseStatementNode(XMLStatementBuilder.java:102)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildStatementFromContext(XMLMapperBuilder.java:138)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.buildStatementFromContext(XMLMapperBuilder.java:131)
	at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:121)
	... 25 more
Caused by: org.apache.ibatis.type.TypeException: Could not resolve type alias 'MyEntity'.  Cause: java.lang.ClassNotFoundException: Cannot find class: MyEntity
	at org.apache.ibatis.type.TypeAliasRegistry.resolveAlias(TypeAliasRegistry.java:120)
	at org.apache.ibatis.builder.BaseBuilder.resolveAlias(BaseBuilder.java:149)
	at org.apache.ibatis.builder.BaseBuilder.resolveClass(BaseBuilder.java:116)
	... 29 more
Caused by: java.lang.ClassNotFoundException: Cannot find class: MyEntity
	at org.apache.ibatis.io.ClassLoaderWrapper.classForName(ClassLoaderWrapper.java:196)
	at org.apache.ibatis.io.ClassLoaderWrapper.classForName(ClassLoaderWrapper.java:89)
	at org.apache.ibatis.io.Resources.classForName(Resources.java:261)
	at org.apache.ibatis.type.TypeAliasRegistry.resolveAlias(TypeAliasRegistry.java:116)
	... 31 more
```
*Redacted stacktrace*

The error stems from this [MyBatisRecorder.createSqlSessionFactory](https://github.com/quarkiverse/quarkus-mybatis/blob/1b42db1aa6a92fda4563d02e4b95e75fed891917/mybatis/runtime/src/main/java/io/quarkiverse/mybatis/runtime/MyBatisRecorder.java#L62), because it tries to resolve aliases when parsing XML mappers, but this configuration is unaware of the `mybatis-config.xml` and therefore doesn't know about type aliases packages.

It should be possible to reproduce this issue by using XML based configuration and using an XML mapper that includes a custom type alias :
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="org.acme.mapper.MyMapper">
    <select id="select" resultType="MyEntity"/>
</mapper>

```

The root cause seems to be that [MyBatisProcessor](https://github.com/quarkiverse/quarkus-mybatis/blob/1b42db1aa6a92fda4563d02e4b95e75fed891917/mybatis/deployment/src/main/java/io/quarkiverse/mybatis/deployment/MyBatisProcessor.java#L189) calls createSqlSessionFactory for each datasource wihtout testing if XML configuration is enabled.

**Comment by zhfeng** [comment]
Thanks @9too for reporting this issue and nice investigating. I will take a look.

**Comment by zhfeng** [comment]
Could you provide a simple reproduce project that would be very helpful ? Thanks.

**Comment by 9too** [comment]
Of course, here it is : https://github.com/9too/quarkus-mybatis-issue-114

**Comment by zhfeng** [comment]
Nice and I will check with it.

**Comment by zhfeng** [comment]
OK, I can re-produce the issue on my local machine. And I found that we produce a SqlSessionFactory for xml configuration with the dataSource name ```xmlconfig``` which should be improved to get the property db of <dataSource> from the mybatis-config.xml. I just push a fix for #115 and I have test with this fix and a little change with MyMapper.java
```
package org.acme.project.mapper;

import org.acme.project.entity.MyEntity;
import org.apache.ibatis.annotations.Mapper;
import io.quarkiverse.mybatis.runtime.meta.MapperDataSource;

@Mapper
@MapperDataSource("xmlconfig")
public interface MyMapper
{
    MyEntity select();
}
```
That could fix your issue.

Anyway I will creat a following issue to fix the  dataSource issue in xml configuration.

**Comment by 9too** [comment]
Sorry for the delay, I've updated quarkus to 2.4.0 and mybatis plugin to 0.0.10 in the sample project and the same error happens.

**Comment by zhfeng** [comment]
Can you apply the following code snippet to see if it works ? Thanks !

I think you have to use ```@MapperDataSource("xmlconfig")``` to specify the dataSource which uses the mybatis.xml configuration. I will try to improve it in the next release for easiler using. Any idea ?
```
@Mapper
@MapperDataSource("xmlconfig")
public interface MyMapper
{
    MyEntity select();
}
```

**Comment by 9too** [comment]
I've finally been able to come back to the relevant project and test this again.
So indeed `@MapperDataSource("xmlconfig")` does the trick and fixes the issue.

Of course it would be great if it was detected automatically simply by using application.properties and not have to specify `@MapperDataSource`, but for now the annotation works just fine.

I would assume that if someone enables `quarkus.mybatis.xmlconfig.enable` they would configure all their datasources wihtin the xml file. So only the xml source could be considered for resolving the correct datasource ?

In any cases I consider this issue solved, thank you for your support !

**Comment by zhfeng** [comment]
Thanks @9too !

I think if  ```quarkus.mybatis.xmlconfig.enable```, you need to specify the datasource in ```mybatis-config.xml``` just like

```xml
   <environments default="development">
        <environment id="development">
            <transactionManager type="JDBC"/>
            <dataSource type="QUARKUS">
                <property name="db">myDS</property>
            </dataSource>
        </environment>
    </environments>
```

And in application.properties, you have to define ```myDS``` like

```
quarkus.datasource.myDS.db-kind=h2
quarkus.datasource.myDS.jdbc.url=jdbc:h2:tcp://localhost/mem:default
```

It needs to parse the ```mybatis-config.xml``` to detect the ```db``` property at build time and produce the ```SqlSessionFactory``` from xml configuration and with the name of  ```myDS```. But currently it is always with the name ```xmlconfig```.

If we do not want to parse the ```mybatis-config.xml```, the simple way could be to set
```
quarkus.mybatis.xmlconfig.datasource=myDS
```
and the only problem is that when the customer make a mistake with ```quarkus.mybatis.xmlconfig.datasource```, that would be a confusion at runtime.
