### ISSUE TITLE
java.lang.ClassNotFoundException: org.acme.mybatis.config.PageConfigurationFactory

### ISSUE THREAD

**Issue by hjh7516** [quarkiverse/quarkus-mybatis#200]
**quarkus version :** 2.9.2.Final
**quarkus-mybatis version :** 1.0.3
When I use quarkus. Mybatis. Configuration-factory to configure a custom ConfigurationFactory, then start the application throws java.lang.ClassNotFoundException

**Comment by hjh7516** [comment]
I think the reason for the problem of the product is that Class#forName( is used when loading the class. If Resources#classForName is used to load the class, this problem can be solved

**Comment by zhfeng** [comment]
@hjh7516 can you provide a re-producer or test? I can take a deep look at it. Thanks!

**Comment by hjh7516** [comment]
**re-producer step：**
1. Create a new class with an arbitrary name. For my example, the contents of this class are shown below
    
![image](https://user-images.githubusercontent.com/33256886/173042151-7f26c168-000e-44f3-90f6-a63eac3fdd4d.png)
2.Use this class to configure in the configuration file(application.properties), as shown below:
![image](https://user-images.githubusercontent.com/33256886/173042496-d4b4ada7-02d7-422e-aecd-b25e039883b0.png)
3.Then start app

**Expected behavior**
The application can start normally
**Actual behavior**
Exception is thrown.
`Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.acme.mybatis.config.PageConfigurationFactory
	at io.quarkiverse.mybatis.runtime.MyBatisRecorder.lambda$setupConfiguration$3(MyBatisRecorder.java:344)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.quarkiverse.mybatis.runtime.MyBatisRecorder.setupConfiguration(MyBatisRecorder.java:340)
	at io.quarkiverse.mybatis.runtime.MyBatisRecorder.createSqlSessionFactory(MyBatisRecorder.java:83)
	at io.quarkus.deployment.steps.MyBatisProcessor$generateSqlSessionFactory1685105135.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.MyBatisProcessor$generateSqlSessionFactory1685105135.deploy(Unknown Source)
	... 16 more`



> @hjh7516 can you provide a re-producer or test? I can take a deep look at it. Thanks!
