### ISSUE TITLE
Cannot use @InjectMock with mybatis Mapper interfaces

### ISSUE THREAD

**Issue by Leibnizhu** [quarkiverse/quarkus-mybatis#217]
I'm trying to mock a mybatis Mapper interface for unit test.

The mapper interface is like :

```java
@Mapper
public interface XxxMapper  {
   @Select("SELECT count(*) FROM xxx")
    long count();
}
```

unit test:

```java
@QuarkusTest
public class XxxServiceTest {
    @InjectMock
    XxxMapper xxxMapper;

    @Test
    void countTest() {
        Mockito.when(xxxMapper.count()).thenReturn(100L);
        System.out.println(xxxMapper.count());
    }
}
```

Running this test will fail with :

```log
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:793)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:752)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
        ..............
Caused by: java.lang.IllegalStateException: Invalid use of io.quarkus.test.junit.mockito.InjectMock - the injected bean does not declare a CDI normal scope but: javax.inject.Singleton. Offending field is xxxMapper of test class class com.github.leibnizhu.XxxServiceTest
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.getBeanInstance(CreateMockitoMocksCallback.java:115)
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.afterConstruct(CreateMockitoMocksCallback.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.initTestState(QuarkusTestExtension.java:782)
	... 65 more
```

As https://quarkus.io/guides/getting-started-testing#further-simplification-with-injectmock said:

> By default, the @InjectMock annotation can be used for any normal CDI scoped bean (e.g. @ApplicationScoped, @RequestScoped). Mocking @Singleton beans can be performed by setting the convertScopes property to true (such as @InjectMock(convertScopes = true). This will convert the @Singleton bean to an @ApplicationScoped bean for the test.

I tried `convertScopes = true` : 

```java
    @InjectMock(convertScopes = true)
    XxxMapper xxxMapper;
```

but the test still failed with the same error.

**Comment by abondar24** [comment]
facing the same issue

**Comment by abondar24** [comment]
Workaround is to mock mapper using Mockito.mock(), but some of my tests fail because mock returns null value

**Comment by zhfeng** [comment]
@abondar24 Nice catch! and is it possible to share your test? And I think it could be very helpful for other people. Also the contribution is welcome!

**Comment by abondar24** [comment]
@zhfeng here is a test: https://github.com/abondar24/QuarkusDemo/blob/master/src/test/java/org/abondar/experimental/quarkusdemo/service/PersonServiceTest.java
Some failing tests are disabled now.

**Comment by renemarkvard-sosint** [comment]
I'm facing the same issue. Unfortunately the Mockito.mock() and MockitoAnnotations.openMocks(this) does not work!

The mocks are created in the test class, but they are not injected into the test-subject (the object @Inject'ed into the test-class).
.. at least that is what I'm seeing - but is also alligns with why your test in the example is failing.
When I reproduce the linked example my mappers in my service are actual MyBatis mapperProxy instanses and NOT the expected Mockito mocks.

The issue we are facing is described in this bug: https://github.com/quarkusio/quarkus/issues/40152
.. and it does not seem that the Quarkus Devs think that fixing this is worth the effort.

One fix is changing the MapperProxies to be @ApplicationScoped and not @Singleton.
.. I have no clue if this is even possible.

**Comment by renemarkvard-sosint** [comment]
@zhfeng 

Any feedback to my comment above?
It seems to be here that the singleton scope is defined:
https://github.com/quarkiverse/quarkus-mybatis/blob/master/mybatis/deployment/src/main/java/io/quarkiverse/mybatis/deployment/MyBatisProcessor.java#L298
.. also line 308, 318 and 335

Any reason not to use ApplicationScoped?

The difference being that applicationscoped beans are wrapped in a proxy - Singletons are not.

It would be very nice to be able to mock these mappers!

**Comment by renemarkvard-sosint** [comment]
@zhfeng 

PR for master created. This is NOT tested as I'm using 2.2.4 - please backport this!
I've made these changes for 2.2.4 tag and tested these locally - both tested my mappers with H2 and tested my service with Mocked version of mappers. All tests success.

https://github.com/quarkiverse/quarkus-mybatis/pull/539

**Comment by zhfeng** [comment]
Since we have not a branch for `2.x`, I will do a new release to include this fix.

**Comment by zhfeng** [comment]
This fix should be in `2.3.1` release.
