### ISSUE TITLE
Seems like not support the dynamic sql while running native?

### ISSUE THREAD

**Issue by Gloduck** [quarkiverse/quarkus-mybatis#36]
If i want to use annotation like `@SelectProvider` . It can successfully running in jvm,but running native i get Error like this:
```java
java.lang.NoSuchMethodException: org.apache.ibatis.annotations.SelectProvider.type()
	at java.lang.Class.getMethod(DynamicHub.java:1089)
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.getProviderType(ProviderSqlSource.java:240)
	at org.apache.ibatis.builder.annotation.ProviderSqlSource.<init>(ProviderSqlSource.java:103)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.buildSqlSource(MapperAnnotationBuilder.java:630)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.lambda$parseStatement$2(MapperAnnotationBuilder.java:301)
	at java.util.Optional.ifPresent(Optional.java:183)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parseStatement(MapperAnnotationBuilder.java:300)
	at org.apache.ibatis.builder.annotation.MapperAnnotationBuilder.parse(MapperAnnotationBuilder.java:132)
	at org.apache.ibatis.binding.MapperRegistry.addMapper(MapperRegistry.java:72)
	at org.apache.ibatis.session.Configuration.addMapper(Configuration.java:841)
	at io.quarkiverse.mybatis.runtime.MyBatisRecorder.createSqlSessionFactory(MyBatisRecorder.java:52)
	at io.quarkus.deployment.steps.MyBatisProcessor$generateSqlSessionFactory112247604.deploy_0(MyBatisProcessor$generateSqlSessionFactory112247604.zig:100)
	at io.quarkus.deployment.steps.MyBatisProcessor$generateSqlSessionFactory112247604.deploy(MyBatisProcessor$generateSqlSessionFactory112247604.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:631)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

```
Are there any solutions to this problem?

**Comment by zhfeng** [comment]
@Gloduck the work around looks like to add SelectProvider to the reflective class items. I will take a look.

**Comment by zhfeng** [comment]
@Gloduck I just release quarkus-mybatis 0.0.4 and can you try it to see if it works ? Thanks !
