### ISSUE TITLE
Error: ... because 'http' access is not allowed due to restriction set by the accessExternalDTD property

### ISSUE THREAD

**Issue by draccagni** [quarkiverse/quarkus-mybatis#85]
Hello,
I'm tring to use mybatis in a Quarkus project built in native mode. When I load an xml mapping file, the following errore is raised:
```
org.apache.ibatis.builder.BuilderException: Error creating document instance.  Cause: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 108; External DTD: Failed to read external DTD 'mybatis-3 -mapper.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.
  at org.apache.ibatis.parsing.XPathParser.createDocument(XPathParser.java:263)                                                                                                                               
  at org.apache.ibatis.parsing.XPathParser.(XPathParser.java:127)                                                                                                                                       
  at org.apache.ibatis.builder.xml.XMLMapperBuilder.(XMLMapperBuilder.java:81)
```

The code snippet that I use to load the mapping file is:
```
Configuration configuration = new Configuration();
String mapperResourceName = "mybatis/test.xml";
InputStream inputStream = Thread.currentThread().getContextClassLoader().getResourceAsStream(mapperResourceName);
XMLMapperBuilder mapperParser = new XMLMapperBuilder(inputStream, configuration, mapperResourceName,
						configuration.getSqlFragments());
mapperParser.parse();
MappedStatement  mappedStatement = configuration.getMappedStatement("test");
BoundSql boundSql = mappedStatement.getBoundSql(params);
```

while the mapper file is:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="Test">
    <select id="test" >
        SELECT t
        FROM Test t
    </select>
</mapper>
```

I have already tried to add
```
<quarkus.native.additional-build-args>-J-Djavax.xml.accessExternalDTD=all</quarkus.native.additional-build-args>
```

without success.

**Comment by zhfeng** [comment]
I just fix https://github.com/quarkiverse/quarkus-mybatis/issues/9 to support xml configuration.

So have you ever try the SNAPSHOT from master branch ? and use the following options in application.properties
```
quarkus.mybatis.xmlconfig.enable=true
quarkus.mybatis.xmlconfig.path=mybatis-config.xml
```

and please check the example xml configuration.
```
<!DOCTYPE configuration
        PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-config.dtd">
<configuration>
    <typeHandlers>
        <package name="io.quarkiverse.it.mybatis"/>
    </typeHandlers>
    <!-- setup environment with Quarkus data source -->
    <environments default="development">
        <environment id="development">
            <transactionManager type="JDBC"/>
            <dataSource type="QUARKUS">
                <property name="db" value="h2"/>
            </dataSource>
        </environment>
    </environments>
    <mappers>
        <package name="io.quarkiverse.it.mybatis"/>
    </mappers>
</configuration>
```

**Comment by draccagni** [comment]
Unfortunately fix #9 doesn't solve my issue. I use mybatis just to load and build a MappedStatement that uses the XPathParser to build it from xml, but raises the exception above.

**Comment by zhfeng** [comment]
OK, I see and could you share us with a simple re-producer project ? I'd like to take a close look.

**Comment by zhfeng** [comment]
And this exception only happens in native build ?

**Comment by draccagni** [comment]
Yes, it happens only in native build. In dev mode the problem is not present. I will provide you a re-producer project ASAP.

**Comment by draccagni** [comment]
I have found how to solve the problem: in the Dockerfile.native file it is necessary to add -Djavax.xml.accessExternalDTD=all on application launching.

You can find the re-producer project at https://github.com/draccagni/quarkus-hibernate-orm-mybatis-3

**Comment by zhfeng** [comment]
Thanks @draccagni and could this issue be closed ?
